# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cf9ba2a6fba02b98b1a792b97a6d4d8ac2689661b925ba8ab0aa83d50bb2d7eaf2980d95a696366deecb12a4a30f8b8bc0c8033ead4c355cda0a9c6a33edb61

test:
  secret_key_base: f9cc18ec47a970f280622791cf8d5abb25aa0d17f83b48fd6063359e6838b06b2237f6dc378b178431bc626a41a4b85e64d67aa790f5014198ef198a1454c6c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
